import { STICKER_REGISTRY } from '../stickers/registry';
import type { TemplateSchema } from './types';

function stickerSource(id: string): string {
  const item = STICKER_REGISTRY.find((sticker) => sticker.id === id);
  return item?.svgSource ?? '';
}

export const BUILTIN_TEMPLATES: TemplateSchema[] = [
  {
    version: 1,
    meta: {
      id: 'tpl_ecommerce_flash_sale',
      name: '带货-限时爆款',
      category: 'ecommerce',
      thumbnail: 'flash-sale',
      author: 'system',
      updatedAt: '2026-05-19T00:00:00.000Z',
    },
    canvas: { width: 1080, height: 1920, backgroundColor: '#fff3e8' },
    theme: { primary: '#ff4d4f', accent: '#fa8c16', text: '#1f1f1f' },
    elements: [
      {
        id: 'tpl1_title',
        type: 'text',
        name: '主标题',
        x: 80,
        y: 180,
        width: 920,
        height: 140,
        rotation: 0,
        scaleX: 1,
        scaleY: 1,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 0,
        content: '今日限时 5 折',
        fontFamily: '"Microsoft YaHei", "PingFang SC", sans-serif',
        fontSize: 90,
        fontWeight: 'bold',
        lineHeight: 1.2,
        textAlign: 'center',
        fill: '#cf1322',
      },
      {
        id: 'tpl1_subtitle',
        type: 'text',
        name: '副标题',
        x: 120,
        y: 360,
        width: 840,
        height: 90,
        rotation: 0,
        scaleX: 1,
        scaleY: 1,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 1,
        content: '库存告急，错过再等一周',
        fontFamily: '"Microsoft YaHei", "PingFang SC", sans-serif',
        fontSize: 44,
        fontWeight: 'normal',
        lineHeight: 1.3,
        textAlign: 'center',
        fill: '#434343',
      },
      {
        id: 'tpl1_sticker',
        type: 'sticker',
        name: '价格标签 1',
        x: 780,
        y: 520,
        width: 220,
        height: 220,
        rotation: -8,
        scaleX: 1,
        scaleY: 1,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2,
        assetId: 'price_tag_1',
        assetType: 'svg',
        assetSource: stickerSource('price_tag_1'),
      },
    ],
  },
  {
    version: 1,
    meta: {
      id: 'tpl_ecommerce_price_compare',
      name: '带货-价格对比',
      category: 'ecommerce',
      thumbnail: 'price-compare',
      author: 'system',
      updatedAt: '2026-05-19T00:00:00.000Z',
    },
    canvas: { width: 1080, height: 1920, backgroundColor: '#f6ffed' },
    theme: { primary: '#389e0d', accent: '#73d13d', text: '#262626' },
    elements: [
      {
        id: 'tpl2_title',
        type: 'text',
        name: '主标题',
        x: 100,
        y: 220,
        width: 880,
        height: 120,
        rotation: 0,
        scaleX: 1,
        scaleY: 1,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 0,
        content: '到手价直降 120 元',
        fontFamily: '"Microsoft YaHei", "PingFang SC", sans-serif',
        fontSize: 78,
        fontWeight: 'bold',
        lineHeight: 1.2,
        textAlign: 'center',
        fill: '#237804',
      },
      {
        id: 'tpl2_badge',
        type: 'sticker',
        name: '推荐章 1',
        x: 120,
        y: 520,
        width: 180,
        height: 180,
        rotation: -6,
        scaleX: 1,
        scaleY: 1,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 1,
        assetId: 'badge_1',
        assetType: 'svg',
        assetSource: stickerSource('badge_1'),
      },
      {
        id: 'tpl2_note',
        type: 'text',
        name: '卖点',
        x: 300,
        y: 540,
        width: 640,
        height: 100,
        rotation: 0,
        scaleX: 1,
        scaleY: 1,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2,
        content: '官方旗舰店，24h 发货',
        fontFamily: '"Microsoft YaHei", "PingFang SC", sans-serif',
        fontSize: 40,
        fontWeight: '500',
        lineHeight: 1.3,
        textAlign: 'left',
        fill: '#262626',
      },
    ],
  },
  {
    version: 1,
    meta: {
      id: 'tpl_store_review_city_pick',
      name: '探店-城市必吃榜',
      category: 'store-review',
      thumbnail: 'city-pick',
      author: 'system',
      updatedAt: '2026-05-19T00:00:00.000Z',
    },
    canvas: { width: 1080, height: 1920, backgroundColor: '#e6fffb' },
    theme: { primary: '#08979c', accent: '#13c2c2', text: '#1f1f1f' },
    elements: [
      {
        id: 'tpl3_title',
        type: 'text',
        name: '主标题',
        x: 80,
        y: 180,
        width: 920,
        height: 120,
        rotation: 0,
        scaleX: 1,
        scaleY: 1,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 0,
        content: '本地人私藏小馆',
        fontFamily: '"Microsoft YaHei", "PingFang SC", sans-serif',
        fontSize: 82,
        fontWeight: 'bold',
        lineHeight: 1.2,
        textAlign: 'center',
        fill: '#006d75',
      },
      {
        id: 'tpl3_star',
        type: 'sticker',
        name: '星标 1',
        x: 180,
        y: 380,
        width: 160,
        height: 160,
        rotation: -12,
        scaleX: 1,
        scaleY: 1,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 1,
        assetId: 'star_1',
        assetType: 'svg',
        assetSource: stickerSource('star_1'),
      },
      {
        id: 'tpl3_subtitle',
        type: 'text',
        name: '副标题',
        x: 280,
        y: 420,
        width: 640,
        height: 100,
        rotation: 0,
        scaleX: 1,
        scaleY: 1,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2,
        content: '人均 50 元，排队也要吃',
        fontFamily: '"Microsoft YaHei", "PingFang SC", sans-serif',
        fontSize: 42,
        fontWeight: '500',
        lineHeight: 1.3,
        textAlign: 'left',
        fill: '#262626',
      },
    ],
  },
];
